var data = {
  "title": "Brazilian Miracle",
  "path": "assets/brazilian-miracle/desktop/",
  "slides":
    [
      {"image": "handwax2.gif",
        "text": "No I didn’t get a nudie wax. Way better.",
        "alt-text": "turquoise hand waxes hair off of an abstract skin surface",
        "audio":"",
      },
      {"image": "eyeblink.gif",
        "text": "My eyesight came back in my right eye.",
        "alt-text": "eyelid slowly blinks over a brown eye",
      },
      {"image": "birds.gif",
        "text": "Una Miracolo.",
        "alt-text": "doves fly out of the center of the eyes pupil",
        "audio":"",
      },
      {"image": null,
        "text": "Don’t tell the media.",
        "alt-text": "no illustration",
        "audio":"",
      },
      {"image": "fireworks_wideshot.gif",
        "text": "I went to the symphony of fireworks off English Bay.",
        "alt-text": "A silhouette of Hansu in a wheel chair is visible from behind. A firework display is seen in the sky in many colors.",
        "audio":"",
      },
      {"image": "FireworksandBun.gif",
        "text": "Between the bangs and the flashes breaking up at my nose...",
        "alt-text": "Hansu's top bun is in the lower frame. We've moved closer in to the fireworks which continue to take up most of the frame.",
        "audio":"",
      },
      {"image": "raindrops.gif",
        "text": "I started to feel a bit odd.\nLight came up in my eye and it started to get stronger.",
        "alt-text": "Multicolored raindrops fill the illustration. They move together and crash to form smaller dots of color that merge and dissappear.",
        "audio":"",
      },
      {"image": "flag.gif",
        "text": "Thank you, Brazil.",
        "alt-text": "No illustration.",
        "audio":"",
      },
      {"image": "newspapereye.gif",
        "text": "MIRACOLO! MIRACOLO!\nHELEN KELLER! CALL POPE!",
        "alt-text": "A newspaper heading is seen with Hansu's writing as the title. The doves have returned. flying out of an eye which is the illustration for the article.",
        "audio":"",
      },
        {"image": null,
        "text": "Still true to this day. Say what?",
        "alt-text": "No illustration.",
        "audio":"",
      },
    ],
}

