var data = {
  "title": "Brazilian Miracle",
  "path": "assets/metamorphosis/desktop/",
  "slides":
    [
      {"image": null,
        "text": "Been pondering the metamorphoses of our bodies… Mine went from ova, to curly legged baby to a gawky 5 foot 7 teen. ",
        "alt-text": "",
      },
      {"image": null,
        "text": "Rounded out into a middle aging beauty then onto my least favorite so far: this hemiplegic tourist and foreigner in the getting real old camp.",
        "alt-text": "",
      },
      {"image": null,
        "text": "Not liking it so much. Younger was way better. There's all this bull floating about getting wiser.",
      },
       {"image": null,
        "text": "Lemme Finish.",
      },
      {"image": null,
        "text": "I am very grateful and thrilled to have these bodies clad about me and I apologize to the opportunistic sperm starter kit if I cast aspersions on its motives. Life was the motive.",
      },
      {"image": null,
        "text": "As I sit here with a sore now bony ass, I sure would have it another way. Yet if this is what is available to me, I happily inhabit it.",
      },
      {"image": null,
        "text": "Some buddha sort said pain is inevitable, suffering optional. Horse manure. Pain hurts.",
      },
      {"image": null,
        "text": "Since we have stainless steel why ain't our teeth made of it? ",
      },
      {"image": null,
        "text": "And why can’t puke come out your bum and furthermore? ",
      },
      {"image": null,
        "text": "You know what really bugs me? The Universe.",
      },
    ],
}
